[package]
name = "npy"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
csv = "1.4.0"
indicatif = "0.18.3"
regex = "1.12.2"
scraper = "0.24.0"
serde_json = "1.0.145"